### ISSUE TITLE
[Bug]: HttpError: t.headers is not iterable

### ISSUE THREAD

**Issue by adam248** [RapidAPI/feedback#72]
### What happened?

We have discovered a bug that seems to be caused by this VS Code extension.

Somehow RapidAPI is interfering with Github API calls by other VS Code extensions.

Please review the following issue...

https://github.com/microsoft/vscode/issues/163214

Thank you. 

### Steps to reproduce?

1. Have the extension installed
2. Try any Github initialization API calls ei. Publich Branch in Source Control or Open a Remote Repo or Clone from Github
3. Also causes the same error with Choose a License vs extension.

### VS Code version

1.72.0

### Extension version

1.6.0

### Relevant log output

```shell
ERR [Extension Host] HttpError: t.headers is not iterable
	at c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:25264
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async p.GithubRemoteSourceProvider.getUserRemoteSources (c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:410637)
	at async Promise.all (index 1)
	at async p.GithubRemoteSourceProvider.getRemoteSources (c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:410423)
	at async c.query (c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git-base\dist\extension.js:1:11370)
workbench.desktop.main.js:87 [Extension Host] HttpError: t.headers is not iterable
	at c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:25264
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async p.GithubRemoteSourceProvider.getUserRemoteSources (c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:410637)
	at async Promise.all (index 1)
	at async p.GithubRemoteSourceProvider.getRemoteSources (c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:410423)
	at async c.query (c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git-base\dist\extension.js:1:11370)
```
```

**Comment by Krzyzaku21** [comment]
i have this same bug i found this by 3h... Uninstall app

**Comment by estruyf** [comment]
Thanks @adam248 and @Krzyzaku21 we will look into this.

**Comment by estruyf** [comment]
Issue is related to the **GitHub Repositories** extension [#262](https://github.com/microsoft/vscode-remote-repositories-github/issues/262). Currently looking into what is causing the `t.headers` issue, as none of our extension code gets executed (tested by removing all functionality, and even then, it occurs).

**Comment by joyceerhl** [comment]
👋 from the callstack above, this is not the GitHub Repositories extension, it's the built-in GitHub extension. I have transferred  https://github.com/microsoft/vscode-remote-repositories-github/issues/262 to the `microsoft/vscode` repo.

```
ERR [Extension Host] HttpError: t.headers is not iterable
	at c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:25264
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async p.GithubRemoteSourceProvider.getUserRemoteSources (c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:410637)
	at async Promise.all (index 1)
	at async p.GithubRemoteSourceProvider.getRemoteSources (c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:410423)
	at async c.query (c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git-base\dist\extension.js:1:11370)
workbench.desktop.main.js:87 [Extension Host] HttpError: t.headers is not iterable
	at c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:25264
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async p.GithubRemoteSourceProvider.getUserRemoteSources (c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:410637)
	at async Promise.all (index 1)
	at async p.GithubRemoteSourceProvider.getRemoteSources (c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:410423)
	at async c.query (c:\Users\Adam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git-base\dist\extension.js:1:11370)
```

**Comment by estruyf** [comment]
@joyceerhl you're right, had already figured this out, I started from the GitHub Repositories extension, but ended up in the GitHub extension which I have been debugging and found it is related to the `node-fetch` client that is used in both extensions.

**Comment by joyceerhl** [comment]
Are you asking why `@octokit/request` uses `globalThis.fetch` and falls back to `nodeFetch`? I would guess it's because the package has to work in browser, web worker, and node environments.

**Comment by estruyf** [comment]
Ok, that makes sense @joyceerhl that it falls back, although should it also be the case for the `node` package? I see other packages available as well in the `@octokit/request`, for the web it makes sense, but for node, it might be tricky. 

Also having the ability to gain access tokens without consent might be an issue. 🤔

**Comment by estruyf** [comment]
The 1.7.0 release fixes this issue, so you should be able to use GitHub functionalities again.
